version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 11
    commands:
      - npm i npm@latest -g
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync ./dist s3://status.sparcs.org
